[package]
name = "vcsi"
version = "0.1.0"
authors = ["Jonathan Frankel <frankel.jb@gmail.com>"]
edition = "2018"

[dependencies]
dotenv = "0.14.1"
env_logger = "0.6.2"
image = "0.22.1"
log = "0.4.8"
rustfft = "3.0.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

