pub const DEFAULT_ACCURATE_DELAY_SECONDS: f32 = 1.0;
pub const DEFAULT_CONTACT_SHEET_WIDTH: u32 = 1500;
pub const DEFAULT_FRAME_TYPE: Option<u8> = None;
pub const DEFAULT_GRID_HORIZONTAL_SPACING: u32 = 5;
